INSERT INTO Canton (Nombre,IdProvincia) VALUES('Central',1);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Escazú',1);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Desamparados',1);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Puriscal',1);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Tarrazú',1);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Aserrí',1);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Mora',1);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Goicoechea',1);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Santa Ana',1);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Alajuelita',1);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Vázquez De Coronado',1);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Acosta',1);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Tibás',1);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Moravia',1);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Montes De Oca',1);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Turrubares',1);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Dota',1);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Curridabat',1);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Pérez Zeledón',1);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('León Cortés Castro',1);
-- Cantones de Alajuela
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Central',2);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('San Ramón',2);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Grecia',2);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('San Mateo',2);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Atenas',2);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Naranjo',2);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Palmares',2);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Poás',2);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Orotina',2);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('San Carlos',2);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Zarcero',2);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Valverde Vega',2);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Upala',2);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Los Chiles',2);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Guatuso',2);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Río Cuarto',2);
-- Cantones de Cartago
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Central',3);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Paraíso',3);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('La Unión',3);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Jiménez',3);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Turrialba',3);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Alvarado',3);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Oreamuno',3);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('El Guarco',3);
-- Cantones de Heredia
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Central',4);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Barva',4);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Santo Domingo',4);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Santa Barbara',4);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('San Rafael',4);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('San Isidro',4);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Belén',4);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Flores',4);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('San Pablo',4);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Sarapiquí',4);
-- Cantones de Guanacaste
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Liberia',5);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Nicoya',5);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Santa Cruz',5);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Bagaces',5);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Carrillo',5);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Cañas',5);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Abangares',5);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Tilarán',5);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Nandayure',5);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('La Cruz',5);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Hojancha',5);
-- Cantones de San Puntarenas
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Central',6);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Esparza',6);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Buenos Aires',6);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Montes De Oro',6);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Osa',6);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Quepos',6);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Golfito',6);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Coto Brus',6);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Parrita',6);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Corredores',6);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Garabito',6);
-- Cantones de Limón
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Central',7);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Pococí',7);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Siquirres',7);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Talamanca',7);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Matina',7);
INSERT INTO Canton (Nombre,IdProvincia) VALUES('Guácimo',7);
